language: node_js
node_js:
  - '12'

env:
  global:
    - secure: K5sRZBHXcHoYfpYEul1tcK2hOp9QMV/T8xmfj1q20AKzw/+ovbsp+Pdb+PbKFr5vP4eN0ISAeHU3nseMGD9tW6BI/Jf1wW4r7qvGch9eH5v1fpAn7Xxm4AqxusxNck7j4uuo720J5nqioZPUjY5ynlgF0iuGJKjx3YVP7t8W4HQ=
    - secure: NbSFG5O6U/6gBMG42vNoRY7Vt0TrDCGunM6MAsTENoRSAN5JFJ1Ne5HfSmOV4hyT63rSTUbNT1zBmqHCfUpZFp+ynVTS3Fs6jv6qgZSZm6l3k5SW1ZGFbDUjxCWuX2lg6n6dV2LyLTnnONa/U/OAb4FkceW9MeKVNjPNv/uYdEA=

addons:
  firefox: latest
  code_climate:
    repo_token:
      secure: "Qg05d4W5BfhbxXy9E9M8ACo2ULSs6tGL5We3pTCAH+smnCKKjXv5Bl+Tu7fC6Cup15LchVUGOxJ/RqXRWV3YEnwqYYZohj0EZANKedLfI8efFXlY1aIs6g29DbWzoCVbG8EczcNY7thakYzW37xkua3GdywH2s7l384bjCOsVDw="

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
  yarn: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache

before_install:
  - npm install -g yarn

install:
  - yarn install --ignore-engines

stages:
  - test
  - name: npm-release
    if: (tag =~ ^v)
  - name: github-releases
    if: (tag =~ ^v)
  - gh-pages release

jobs:
  include:
    - stage: test
      script:
        - yarn test:ci
      after_script:
        - yarn rewrite-paths
        - codeclimate-test-reporter < coverage/lcov.info
    - stage: npm-release
      script:
        - yarn build
      # Identifies `a.b.c-xxx.n` tags as pre-releases, and `a.b.c` as stable releases
      before_deploy: |
        function npm_dist_tag() {
          if [[ "$TRAVIS_TAG" = *"-"* ]]; then
            echo "next"
          else
            echo "latest"
          fi
        }
      deploy:
        provider: npm
        tag: $(npm_dist_tag)
        email: rwwagner90@gmail.com
        skip_cleanup: true
        api_key:
          secure: "IAnW1q6hsBbeLb+LmjwqXGAb1f+ujfZHQETxkEvOwt9m9SuEu7f+nWMAr2Y8a+5KJ5raMuuER5LCwbRNf4Ygm/wvh+TVVmyOqylVKU5SlTQbWazJSgCaNNNe5fvFSxtleQUqLSeOW1PWxD67KFAlczucmLsNBvdFBn9JxsF4Mrg="
        on:
          branch: master
          tags: true
          repo: shipshapecode/shepherd
        after_deploy: |
          if [ "$(npm_dist_tag)" == "latest" ]; then
            npm dist-tag rm shepherd.js next || true
          fi
    - stage: github-releases
      script:
        - yarn build
      # Identifies `a.b.c-xxx.n` tags as pre-releases, and `a.b.c` as stable releases
      before_deploy: |
        function gh_prerelease() {
          if [[ "$TRAVIS_TAG" = *"-"* ]]; then
            echo true
          else
            echo false
          fi
        }
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        file_glob: true
        file:
          - dist/css/*
          - dist/js/*
        skip_cleanup: true
        prerelease: $(gh_prerelease)
        on:
          tags: true
